[package]
name = "counter"
version = "0.0.1"
authors = ["you"]

[dependencies]
# Pull in the Aptos framework source so std modules (signer, vector, etc.) are available.
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[addresses]
# standard library / framework live at 0x1 on Aptos
std = "0x1"
AptosFramework = "0x1"
Counter = "0xe18dc5a360217fe88b3ad2b6d442d534fc6636598595ef8e5f37a4899706dc52"
