[package]
name = "todo_list"
version = "0.0.0"

[addresses]
todo_addr = "0x62a1eecce8a83f14f0b1909d3147d465a866fd231f21ca53f78114287dc47d86"

# ðŸ‘‰ This line is CRITICAL: it tells Move what `std::` refers to
std = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
