[package]
name = "project"
version = "1.0.0"
authors = []

[addresses]
project = "0x2d7ee8fb476be48309205977888f6d3e74fe348cc804b26288f35e6b32338549"

[dev-addresses]
project = "0x2d7ee8fb476be48309205977888f6d3e74fe348cc804b26288f35e6b32338549"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
